# Copyright 2023 Google LLC

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

#     https://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Vendored Dinosaur dycore implementation used by Dynamaxx."""

from dynamaxx.dycore.models.dinosaur import (
    associated_legendre,
    coordinate_systems,
    filtering,
    fourier,
    held_suarez,
    horizontal_interpolation,
    hybrid_coordinates,
    jax_numpy_utils,
    layer_coordinates,
    leapfrog_utils,
    primitive_equations,
    primitive_equations_states,
    pytree_utils,
    radiation,
    scales,
    shallow_water,
    shallow_water_states,
    sigma_coordinates,
    spherical_harmonic,
    time_integration,
    typing,
    units,
    vertical_interpolation,
    weatherbench_utils,
    xarray_utils,
)
from dynamaxx.dycore.models.dinosaur.adapter import (
    DEFAULT_SEMI_IMPLICIT_OFFCENTERING,
    DinosaurPrimitiveEquationsDycoreModel,
    analysis_2m_initialized_land_skin_dinosaur_dycore_model,
    analysis_offset_held_suarez_equilibrium_dinosaur_dycore_model,
    anticipated_pv_flux_dinosaur_dycore_model,
    bulk_richardson_2m_temperature_diagnostic_dinosaur_dycore_model,
    coriolis_split_dinosaur_dycore_model,
    coriolis_strang_split_dinosaur_dycore_model,
    default_dinosaur_dycore_model,
    digital_filter_dinosaur_dycore_model,
    digital_filter_surface_residual_dinosaur_dycore_model,
    dry_static_energy_hsl_transport_dinosaur_dycore_model,
    ekman_coupled_dinosaur_dycore_model,
    ekman_depth_dinosaur_dycore_model,
    horizontal_semilagrangian_theta_transport_dinosaur_dycore_model,
    hydrostatic_temperature_initialization_dinosaur_dycore_model,
    land_ocean_low_mode_t2m_memory_dinosaur_dycore_model,
    land_sea_surface_temperature_dinosaur_dycore_model,
    late_ramped_land_skin_reservoir_dinosaur_dycore_model,
    layer_mass_weighted_dse_hsl_transport_dinosaur_dycore_model,
    layer_mean_hydrostatic_temperature_initialization_dinosaur_dycore_model,
    log_pressure_initialization_dinosaur_dycore_model,
    midpoint_semilagrangian_theta_departure_dinosaur_dycore_model,
    ocean_anchor_ri2m_lower_boundary_dinosaur_dycore_model,
    ocean_bulk_sensible_heat_flux_dinosaur_dycore_model,
    orographic_lift_lower_column_wind_dinosaur_dycore_model,
    orographic_lift_theta_dinosaur_dycore_model,
    pressure_ramped_vertical_dse_wtg_dinosaur_dycore_model,
    pressure_thickness_ri2m_temperature_dinosaur_dycore_model,
    prognostic_skin_ri2m_lower_boundary_dinosaur_dycore_model,
    richardson_10m_wind_diagnostic_dinosaur_dycore_model,
    scale_separated_surface_residual_dinosaur_dycore_model,
    semi_implicit_offcenter_dinosaur_dycore_model,
    stability_aware_surface_residual_dinosaur_dycore_model,
    terrain_work_form_drag_heating_dinosaur_dycore_model,
    theta_mean_recenter_dinosaur_dycore_model,
    theta_tendency_dinosaur_dycore_model,
    tropical_wtg_mass_dse_relaxation_dinosaur_dycore_model,
    weak_held_suarez_dinosaur_dycore_model,
    zero_mean_radiative_land_skin_energy_dinosaur_dycore_model,
)

__version__ = "1.3.6"
UPSTREAM_PACKAGE = "dinosaur"
UPSTREAM_VERSION = "1.3.6"

__all__ = [
    "UPSTREAM_PACKAGE",
    "UPSTREAM_VERSION",
    "__version__",
    "DEFAULT_SEMI_IMPLICIT_OFFCENTERING",
    "DinosaurPrimitiveEquationsDycoreModel",
    "analysis_2m_initialized_land_skin_dinosaur_dycore_model",
    "analysis_offset_held_suarez_equilibrium_dinosaur_dycore_model",
    "anticipated_pv_flux_dinosaur_dycore_model",
    "associated_legendre",
    "bulk_richardson_2m_temperature_diagnostic_dinosaur_dycore_model",
    "coordinate_systems",
    "coriolis_split_dinosaur_dycore_model",
    "coriolis_strang_split_dinosaur_dycore_model",
    "default_dinosaur_dycore_model",
    "digital_filter_dinosaur_dycore_model",
    "digital_filter_surface_residual_dinosaur_dycore_model",
    "dry_static_energy_hsl_transport_dinosaur_dycore_model",
    "ekman_coupled_dinosaur_dycore_model",
    "ekman_depth_dinosaur_dycore_model",
    "filtering",
    "fourier",
    "held_suarez",
    "horizontal_semilagrangian_theta_transport_dinosaur_dycore_model",
    "hydrostatic_temperature_initialization_dinosaur_dycore_model",
    "horizontal_interpolation",
    "hybrid_coordinates",
    "jax_numpy_utils",
    "land_ocean_low_mode_t2m_memory_dinosaur_dycore_model",
    "land_sea_surface_temperature_dinosaur_dycore_model",
    "late_ramped_land_skin_reservoir_dinosaur_dycore_model",
    "layer_mass_weighted_dse_hsl_transport_dinosaur_dycore_model",
    "layer_mean_hydrostatic_temperature_initialization_dinosaur_dycore_model",
    "layer_coordinates",
    "leapfrog_utils",
    "log_pressure_initialization_dinosaur_dycore_model",
    "midpoint_semilagrangian_theta_departure_dinosaur_dycore_model",
    "ocean_anchor_ri2m_lower_boundary_dinosaur_dycore_model",
    "ocean_bulk_sensible_heat_flux_dinosaur_dycore_model",
    "orographic_lift_lower_column_wind_dinosaur_dycore_model",
    "orographic_lift_theta_dinosaur_dycore_model",
    "pressure_thickness_ri2m_temperature_dinosaur_dycore_model",
    "pressure_ramped_vertical_dse_wtg_dinosaur_dycore_model",
    "prognostic_skin_ri2m_lower_boundary_dinosaur_dycore_model",
    "primitive_equations",
    "primitive_equations_states",
    "pytree_utils",
    "radiation",
    "richardson_10m_wind_diagnostic_dinosaur_dycore_model",
    "scales",
    "scale_separated_surface_residual_dinosaur_dycore_model",
    "semi_implicit_offcenter_dinosaur_dycore_model",
    "shallow_water",
    "shallow_water_states",
    "sigma_coordinates",
    "spherical_harmonic",
    "stability_aware_surface_residual_dinosaur_dycore_model",
    "terrain_work_form_drag_heating_dinosaur_dycore_model",
    "theta_mean_recenter_dinosaur_dycore_model",
    "theta_tendency_dinosaur_dycore_model",
    "time_integration",
    "tropical_wtg_mass_dse_relaxation_dinosaur_dycore_model",
    "typing",
    "units",
    "vertical_interpolation",
    "weatherbench_utils",
    "weak_held_suarez_dinosaur_dycore_model",
    "xarray_utils",
    "zero_mean_radiative_land_skin_energy_dinosaur_dycore_model",
]
